apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Go Test Publish Results using XML

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Check out a Git repository
      - uses: docker://golang:1.23.2-alpine3.19
        name: build code
        shell: sh
        run: |
            export GOPATH=$HOME/go
            export PATH=$PATH:$GOPATH/bin
            echo $PATH
            go version
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o build/app-main .
            go install github.com/jstemmer/go-junit-report@latest
            go test -v . | go-junit-report > /cloudbees/workspace/test.xml
            cat /cloudbees/workspace/test.xml
      - name: Publish test results
        uses: cloudbees-io/publish-test-results@v1
        with:
          test-type: Go
          folder-name: ${{ cloudbees.workspace }}/test.xml
